### ISSUE TITLE
Give user tx recipt when they broadcast a transaction. 

### ISSUE THREAD

**Issue by barryWhiteHat** [lsankar4033/surrogeth#4]
## Whats the problem ? 

The problem is that when a user broadcasts their transactions they don't have any certinty about it being broadcast. So at the moment we have a kind of spray and pray approach where we keep broadcasting the transaction until it gets mined. 

## Whats the solution

Instead when a user sends a tx to a relayer the relayer should send back the signed transaction with a gasPrice that is non zero and an account that has enough gas to pay it. Then they user can broadcast this transaction themselves. This improves the UX because the wallet can give some information about the transaction aswell as estimate the time to mineing. 

Thier is still the chance that the relayer is cheating and sends multiple transactions with the same nonce and only one of them will be accepted. So its still important to share the tx with multiple relayers.

**Comment by lsankar4033** [comment]
Good point, had been thinking about this... 

I don't think this solution is ideal UX-wise, as the *client* could then get beaten by either:
1. another relayer working with the same withdraw proof
2. another client who receives a signed tx with the same nonce from the relayer

2 is especially egregious, as the client would basically have to keep getting new signed txes from the relayer with new nonces until they happen to not be beaten by another client withdrawing at the same time.

**Comment by barryWhiteHat** [comment]
Agree this is not ideal. But i think its better than the status quo. I would recommend the following logic 

1. Connect to relayer
2. Get transaction with non zero gas price. 
3. Check its valid, 
4. Broadcast that transaction
5. Wait 5 minutes 
6. Check that it has either been mined or that the transaction is still valid. 

If we get to the end with all passing then we know our transaction has been broadcast. But the UX is to basically sit around and wait until it is mined. 

The thing i am worried about in this issue is that we send a tx to a relayer they don't do anything and we just wait for a long time and have not idea what is going on weather the tx has been braodcast. But i guess broadcasting to a bunch of relayers would be a good enough strategy.

**Comment by lsankar4033** [comment]
Ya, I think the burden of waiting has to end up with either the relayer or the user in some sense.

The former happens with the current strategy because the user broadcasts to a bunch of relayers at once and as a result any single relayer can get 'proof-frontrun' by another relayer. The latter happens with your proposed strategy because the user has to sit around, wait, and keep re-submitting txes.

**Comment by lsankar4033** [comment]
Side note: I think these tradeoffs are worth talking about at devcon to solicit more people's opinions on!
